# CA PARAMS: SHARED PARAMETERS FOR BOTH EVALUATION AND CONTROLLER
BITS_PER_VALUE = 5
ROW_LENGTH = 64
NEIGHBORHOOD_RADIUS = 1
NEIGHBORHOOD_SIZE = 2 * NEIGHBORHOOD_RADIUS + 1
NUMBER_OF_CA_TICKS = 20
ACTION_DECODING = "center"

# GA PARAMS
POPULATION_SIZE = 100
NUMBER_OF_GENERATIONS = 100
ELITE_PERCENTAGE = 0.01
TOURNAMENT_SIZE = 3
MUTATION_RATE = 0.02
NUMBER_OF_EPISODES = 10