# CA CONFIGURATION: SHARED PARAMETERS FOR BOTH EVALUATION AND CONTROLLER

BITS_PER_VALUE = 5             # NUMBER OF BITS PER VARIABLE
ROW_LENGTH = 64                # LENGTH OF THE CELLULAR AUTOMATA ROW
NEIGHBORHOOD_RADIUS = 1        # RADIUS FOR THE CA NEIGHBORHOOD
NEIGHBORHOOD_SIZE = 2 * NEIGHBORHOOD_RADIUS + 1
NUMBER_OF_CA_TICKS = 20        # NUMBER OF STEPS (TICKS) TO EVOLVE THE CA (FOR BOTH TRAINING AND CONTROL)
