# ENVIRONMENT

# CA PARAMS: SHARED PARAMETERS FOR BOTH EVALUATION AND CONTROLLER

BITS_PER_VALUE      = 4        # (test only 4, 6, [8]) TESTED
ROW_LENGTH          = 64       # (test only 32, 48, [64]) TESTED
NEIGHBORHOOD_RADIUS = 1        # (test only [1], 2) TESTED
NUMBER_OF_CA_TICKS  = 10       # (test only 5, [10], 15) TESTED
ACTION_DECODING     = "center" # (test only ['center'], 'majority', 'sum') TESTED
NEIGHBORHOOD_SIZE = 2 * NEIGHBORHOOD_RADIUS + 1

# GA PARAMS
POPULATION_SIZE = 20
NUMBER_OF_GENERATIONS = 10
ELITE_PERCENTAGE = 0.1
TOURNAMENT_SIZE = 3
MUTATION_RATE = 0.01


# ENVIRONMENT
NUMBER_OF_EPISODES = 10
MAXIMUM_STEPS_PER_EPISODE = 500